### ISSUE TITLE
Possible transfert of the wayland name on crates.io ?

### ISSUE THREAD

**Issue by elinorbgr** [eyolfson/rust-wayland#2]
Hi, I am the maintainer of [wayland-rs](https://github.com/Smithay/wayland-rs), a group of crates binding to the wayland client and server libs (mostly [wayland-client](https://crates.io/crates/wayland-client) and [wayland-server](https://crates.io/crates/wayland-server)).

As you don't seem to be willing to continue working on this rust-wayland project, would you agree to giving me the [wayland](https://crates.io/crates/wayland) name on crates.io? I would use it to make a meta-package for the different crates in wayland-rs.

Thanks.

**Comment by Kintaro** [comment]
Sorry for the super late reply. Yes, of course you can have that namespace.
I don't know exactly how to do that, but will look it up tomorrow or the
day after.

**Comment by elinorbgr** [comment]
Thanks a lot! Don't worry about the delay, there's nothing pressing.

The procedure is quite simple actually, once logged-in on crates.io, on the page of the crate, there will be a "manage owners" link in the "owners" section of the side-bar.

**Comment by Kintaro** [comment]
Ok, should I transfer it to the mail address you are using right now?

**Comment by elinorbgr** [comment]
I think you can just use my github username, "vberger", crates.io is linked to github authentication.

**Comment by Kintaro** [comment]
Ok, thanks. Sorry for hording the crate name. I originally inteded to
create my own wayland wrapper, but never got around to it

**Comment by elinorbgr** [comment]
@Kintaro uh, actually I didn't realize at first, but the owner of the `wayland` name on crates.io is @eyolfson , not you...

Not sure I get what's going on here.
